CREATE FUNCTION [dbo].[udf_GetEdition]
(
)
RETURNS NVARCHAR(50)
AS
BEGIN
	RETURN (LEFT(CAST(SERVERPROPERTY('edition') AS VARCHAR(100)),CHARINDEX(' ',CAST(SERVERPROPERTY('edition') AS VARCHAR(100)))))
END
