CREATE VIEW [IndexMaint].[vwIndexStatistics]
AS 
	SELECT [IndexStatisticID]
		  ,[DatabaseName]
		  ,[SchemaName]
		  ,[TableName]
		  ,[IndexName]
		  ,[IndexID]
		  ,[IndexDepth]
		  ,[IndexLevel]
		  ,[PartitionNumber]
		  ,[IndexTypeDesc]
		  ,[AllocUnitTypeDesc]
		  ,[AvgFragmentationPercent]
		  ,[AvgPageSpaceUsedPercent]
		  ,[FillFactor]
		  ,[IsDisabled]
		  ,[PageCount]
		  ,[RecordCount]
		  ,[IndexStatus]
		  ,[InsertDate]
		  ,[UpdateDate]
	  FROM [IndexMaint].[Statistics]
GO
